const SYSTEM_EVENTS= {

    // ---RIDE EVENT---
    RIDE_REQUESTED : "RIDE_REQUESTED",
    RIDE_ACCEPTED : "RIDE_ACCEPTED",
    RIDE_STARTED : "RIDE_STARTED",
    RIDE_COMPLETED : "RIDE_COMPLETED",
    RIDE_CANCELLED : "RIDE_CANCELLED",

    // ---DRIVER EVENT---
    DRIVER_ONLINE : "DRIVER_ONLINE",
    DRIVER_OFFLINE : "DRIVER_OFFLINE",
    DRIVER_LOCATION_UPDATED : "DRIVER_LOCATION_UPDATED",

    // ---PAYMENT EVENT---
    PAYMENT_INITIATED : "PAYMENT_INITIATED",
    PAYMENT_SUCCESS : "PAYMENT_SUCCESS",
    PAYMENT_FAILED : "PAYMENT_FAILED"
}

Object.freeze(SYSTEM_EVENTS); // --LOCK SYSTEM EVENT OBJECT--


export {
    SYSTEM_EVENTS
}